name: taskmaster

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    logging:
      driver: syslog
      options:
        syslog-address: "unix:///dev/log"
        tag: "taskmaster"
